gantt
    title Historical/Project Timeline
    dateFormat  YYYY-MM-DD
    section Phase 1: Initiation
    A task           :a1, 2024-01-01, 30d
    Another task     :after a1  , 20d
    section Phase 2: Execution
    Critical Action  :crit, active, 2024-02-20, 24d
    Implementation   :12d
    section Phase 3: Fallout
    Consequences     :24d